### ISSUE TITLE
Incorrect . on a slide

### ISSUE THREAD

**Issue by AndyMcCannNHS** [nhs-r-community/intro-quarto#9]
https://nhs-r-community.github.io/intro-quarto/session-rendering.html#/excluding-files

I think you decided the . in "!.files/" was incorrect?

This is my first GitHub "issue"!

**Comment by Lextuga007** [comment]
Yes I think I did because I'd forgotten that's the folder on my computer so I couldn't see it (because it's excluded!) on GitHub. For course preparation I think I need to move this folder which has all the pre-prepared work to it's own repository for easier downloads #12 That will mean that this document needs to be updated.

Thanks for raising the issue as I would have missed this 😄
